import base64
from datetime import datetime

from github import GithubException

from app.github_integration.client import get_repo
from app.core.state import AgentState


def create_pr_from_state(state: AgentState) -> str:
    """
    Takes a completed AgentState with review_passed=True and:
    1. Creates a new branch
    2. Commits each proposed change to that branch
    3. Opens a PR with agent reasoning in the description
    Returns the PR URL.
    """
    repo = get_repo(state["repo_owner"], state["repo_name"])

    # --- 1. Create a branch off main ---
    branch_name = f"agent/issue-{state['issue_number']}-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}"

    default_branch = repo.default_branch
    source_sha = repo.get_branch(default_branch).commit.sha

    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=source_sha,
    )

    # --- 2. Commit each changed file ---
    for change in state["proposed_changes"]:
        file_path = change["file_path"].replace("\\", "/")  # normalize Windows paths
        new_content = change["content"]

        try:
            # Get current file SHA (needed for update)
            existing = repo.get_contents(file_path, ref=branch_name)
            repo.update_file(
                path=file_path,
                message=f"fix: {state['issue_title']} (closes #{state['issue_number']})",
                content=new_content,
                sha=existing.sha,
                branch=branch_name,
            )
        except GithubException as e:
            if e.status == 404:
                # File doesn't exist yet — create it
                repo.create_file(
                    path=file_path,
                    message=f"feat: {state['issue_title']} (closes #{state['issue_number']})",
                    content=new_content,
                    branch=branch_name,
                )
            else:
                raise

    # --- 3. Build PR description from agent logs ---
    log_lines = "\n".join(
        f"- **[{log['agent']}]** {log['message']}"
        for log in state.get("logs", [])
    )

    pr_body = f"""## 🤖 Auto-generated by Multi-Agent Dev Assistant

**Issue:** #{state['issue_number']} — {state['issue_title']}

### Agent Reasoning Log
{log_lines}

### Files Changed
{chr(10).join(f'- `{c["file_path"]}`' for c in state['proposed_changes'])}

---
*This PR was automatically generated. Please review carefully before merging.*
"""

    # --- 4. Open the PR ---
    pr = repo.create_pull(
        title=f"fix: {state['issue_title']} (closes #{state['issue_number']})",
        body=pr_body,
        head=branch_name,
        base=default_branch,
    )

    return pr.html_url


if __name__ == "__main__":
    # Quick test — creates a real PR on social-dash
    from app.core.state import AgentState

    test_state: AgentState = {
        "issue_number": 99,
        "issue_title": "Test PR from Multi-Agent Dev Assistant",
        "issue_body": "This is a test PR to verify the GitHub integration works correctly.",
        "repo_owner": "VT-2004",
        "repo_name": "social-dash",
        "severity": "attempt",
        "severity_reason": "Test issue.",
        "retrieved_context": [],
        "proposed_changes": [
            {
                "file_path": "AGENT_TEST.md",
                "content": "# Agent Test\n\nThis file was created by the Multi-Agent Dev Assistant to verify GitHub PR creation works.\n",
            }
        ],
        "review_passed": True,
        "review_notes": "Test passed.",
        "retry_count": 0,
        "test_files": [],
        "status": "in_progress",
        "pr_url": None,
        "logs": [
            {
                "agent": "severity_classifier",
                "message": "Classified as 'attempt': Test issue.",
                "timestamp": "2024-01-01T00:00:00",
            },
            {
                "agent": "code_agent",
                "message": "Applied 1 edit(s), 1 file(s) changed.",
                "timestamp": "2024-01-01T00:00:01",
            },
            {
                "agent": "review_agent",
                "message": "Review passed: Test change looks good.",
                "timestamp": "2024-01-01T00:00:02",
            },
        ],
    }

    print("Creating PR...")
    url = create_pr_from_state(test_state)
    print(f"PR created: {url}")